### PR TITLE
remove regex dependency

### PR DESCRIPTION
**Pull request by olsonpm**
I tried updating poetry with the removed 'regex' dependency but the command was on the 7 minute mark before I cancelled the operation because I wasn't going to wait that long just for the dev environment to get set up.  This also means I didn't run the tests.

Anyway, I'll leave this here in case anyone wants to finalize it and confirm the changes work

Closes: #18 #16

### CODE REVIEW

**Comment by pykong** [comment]
@olsonpm Thank you very much for your **PR**. I am going to have a look into it and perform any changes required by myself.

**Comment by AlejandroFrias** [comment]
Thanks for the idea to remove the regex dependency! This is a great start for me to work from. Sorry I've been AWOL for so long1

**Comment by pykong** [comment]
@AlejandroFrias Great to have you back! I am going to do more work on this important library in December.

**Comment by pykong** [comment]
I am merging this into `refactoring`.
I will take it from there.

**Pull request merged**
